### PR TITLE
V1.0.0

### PR DESCRIPTION
**Pull request by tklijnsma**
Somewhat of an overhaul to make this package work in CUDA 11.7 and torch 2.0.

Also made a few other choices to facilitate keeping this package up to date:

- Extensions for accumulate_knn, accumulate_knn_grad, select_knn_grad, and version are dropped from the repo for now. It should be easy to re-add them later, but for now we're not using them at the moment.
- Separate libraries for the cpu and cuda versions of select_knn (rather than doing device checking in C++).
- Synchronize the outputs of the cpu and cuda versions for select_knn; Both versions now return the self-loop at the first index, and -1 for non-edges.
- Remove all code specific to models or HGCAL (GravNet, datasets, object condensation, etc.). This code will be moved to a new repository so that this one can focus on torch extensions.

### CODE REVIEW

File: README.md [hunk 1]
```diff
@@ -1,2 +1,174 @@
...
+
+```bash
+singularity pull docker://pytorch/pytorch:2.0.0-cuda11.7-cudnn8-devel
+singularity run --nv sifs/pytorch_2.0.0-cuda11.7-cudnn8-devel.sif
+```
+
+And then once in the container:
+
+```bash
+export PYTHONPATH="/opt/conda/lib/python3.10/site-packages"
```
Comment (kdlong) [inline README.md:103]: This isn't strictly needed, right? Seems a little dangerous to do this inside of pip

File: README.md [hunk 2]
```diff
@@ -1,2 +1,174 @@
...
+If you only want to test the compilation of the extensions:
+
+```bash
+python setup.py develop
+```
+
+### Containerization
+
+It is recommended to install and run inside a container.
+At the time of writing (29 Sep 2023), the [pytorch/pytorch:2.0.0-cuda11.7-cudnn8-devel](https://hub.docker.com/layers/pytorch/pytorch/2.0.0-cuda11.7-cudnn8-devel/images/sha256-96ccb2997a131f2455d70fb78dbb284bafe4529aaf265e344bae932c8b32b2a4?context=explore)
```
Comment (kdlong) [inline README.md:90]: I set this up successfully on a machine with 1080s at MIT, but on another machine we currently only have drivers that support up to CUDA 11.6. I don't see any PyTorch dockers that support torch 2.0 and CUDA 11.6. Are both required?

File: README.md [hunk 3]
```diff
@@ -1,2 +1,174 @@
...
+pytest tests
+```
+
+
+## Performance
+
+The following profiling code can be used:
+
+```python
+import time
```
Comment (kdlong) [inline README.md:127]: This is useful, maybe it makes more sense to have this as a test script vs. just in the readme.

**Comment by lgray** [comment]
torch 2.0 strict requires cuda >= 11.7

File: README.md (hunk 2 above)
Comment (lgray) [reply README.md:90]: torch 2.0 strictly requires cuda >= 11.7

Comment (kdlong) [reply README.md:90]: Does this implementation require torch2.0? In any case, I was messing around with other containers and concluded this is too much of a pain, I'll use the 1080s for now until we can update the Nvidia drivers on the A30s

Comment (lgray) [reply README.md:90]: Looking at the changes in this PR it doesn't look like it wouldn't compile against torch < 2 and corresponding cuda.

Though, my two cents, it's probably just better to migrate your projects up to torch 2, it's pretty damn sweet featurewise.

Comment (kdlong) [reply README.md:90]: Yeah, I'll use the 1080s until the A30s are updated.

File: README.md (hunk 1 above)
Comment (kdlong) [reply README.md:103]: Ah, ok, I see this is how the singularity is setup, so this is to avoid reinstalling torch with pip. ```python3 -m venv env --system-site-packages``` is another option (likewise safe if you're in the singularity).

File: README.md (hunk 2 above)
Comment (tklijnsma) [reply README.md:90]: For what it's worth, version 0.0.1 should work with torch 1.0... but it also needs CUDA 10 I believe.

File: README.md (hunk 3 above)
Comment (tklijnsma) [reply README.md:127]: I've added it as a separate script. I would rather not add it as a literal test case, since it is not a functional test, just for performance.
